-- Write your PostgreSQL query statement below
SELECT VISITS.CUSTOMER_ID, COUNT(CUSTOMER_ID) AS COUNT_NO_TRANS
FROM VISITS LEFT JOIN TRANSACTIONS ON VISITS.VISIT_ID = TRANSACTIONS.VISIT_ID
WHERE TRANSACTIONS.VISIT_ID IS NULL
GROUP BY VISITS.CUSTOMER_ID;